### ISSUE TITLE
Descriptive names for edit_distance

### ISSUE THREAD

**Issue by boeddeker** [pzelasko/kaldialign#11]
Hello, what do you think about using descriptive names for the arguments of `edit_distance`?
With `descriptive` I mean something like reference and hypothesis.
In the "plain" edit_distance you only count the numbers of errors, and you can switch the arguments.
It changes, once you report ins/del/sub.

While a change of the code arguments would be a breaking change, it would be nice to have it at least in the README and the docsting. I want to use kaldialign to report ins/del/sub, but now I have to think about, which argument is which.

**Comment by pzelasko** [comment]
Sorry missed this one. You have a good point. I'll make the change to `ref` and `hyp`, I doubt anybody is using kwargs `a=` and `b=` :)
