### ISSUE TITLE
Support conda install

### ISSUE THREAD

**Issue by csukuangfj** [pzelasko/kaldialign#7]
@pzelasko 
I think it would be good to support
```
conda install -c kaldialign kaldialign
```

All you need to do is the following two steps I will take care of the rest.

Note: Step 1 is optional. If you don't do it, I will do it.

# Step 1:
Create an account at https://anaconda.org/

The account name MUST be `kaldialign`. Otherwise, it is not possible to use `-c kaldialign`.

After creating the account, visit the following URL:

https://anaconda.org/kaldialign/settings/access

![Screen Shot 2022-10-01 at 16 13 07](https://user-images.githubusercontent.com/5284924/193400042-b729334a-8d60-40c2-a82c-a1d4b055a2b9.png)

You will find the token at the bottom of that page after clicking `Create`.

Click `view` to get its value. (We don't need the name of the API token. Only its value is important).

# Step 2
Visit
https://github.com/pzelasko/kaldialign/settings/secrets/actions

Click the button "New repository secret".

Name of the secret should be: `KALDIALIGN_CONDA_TOKEN`
Value of the secret:  Please paste the value of the API token you copied from step 1.

That is all.

**Comment by pzelasko** [comment]
Thanks @csukuangfj! I will set it all up and let you know when it's done.

**Comment by pzelasko** [comment]
@csukuangfj done, let me know what's next (great tutorial btw)
